name: Integration tests

on:
  pull_request:

jobs:
  integration-tests-bind-operator:
    uses: nrobinaubertin/stable-operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      self-hosted-runner: false
      self-hosted-runner-label: "edge"
      juju-channel: 3.6/stable
      provider: lxd
      working-directory: ./bind-operator
